#################################################
#                 Ipv6 config                   #
#           Author: Mamadou Saliou DIAWARA      #
#################################################

- name: Disable ipv6
  shell: "{{ item }}"
  loop:
  - echo "net.ipv6.conf.all.disable_ipv6 = 1" >>  /etc/sysctl.d/99-sysctl.conf
  - echo "net.ipv6.conf.default.disable_ipv6 = 1" >>  /etc/sysctl.d/99-sysctl.conf
  - echo "net.ipv6.conf.lo.disable_ipv6 = 1" >>  /etc/sysctl.d/99-sysctl.conf
  - sysctl -p
  become: true
- name: Vérification 
  shell: cat /proc/sys/net/ipv6/conf/all/disable_ipv6
  register: result
- debug:
    msg: "{{ result.stdout }}"
    