#################################################
# UFW Config
#################################################
- name: Install iptables and ufw
  apt: name={{ item }} state=installed
  with_items:
    - nftables
    - iptables
    - iptables-persistent
    - netfilter-persistent
    - whois
    - ufw

- name: install ufw
  shell: "{{ item }}"
  loop:
  - ufw enable
  - ufw status

- name : Enable UFW and close all ports
  ufw: state=enabled policy=deny

- name : Allow all access to tcp port SSH_PORT, 80 and 443
  ufw: rule=allow port={{item}} proto=tcp
  with_items: [ "{{ SSH_PORT }}" ,80,443]

- name : Allow range port
  ufw: rule=allow port=60000:61000 proto=tcp

- name: Set logging
  community.general.ufw:
    logging: 'on'
    
- name: Enable iptables-legacy for ipv4
  command: update-alternatives --set iptables /usr/sbin/iptables-nft

- name: Enable iptables-legacy for ipv6
  command: update-alternatives --set ip6tables /usr/sbin/ip6tables-nft


- name: Install sendmail and IPtables-persistent
  command: apt install sendmail iptables-persistent -y
  become: true

- name: Setup Firewall
  command: ptables -A INPUT {{item}}
  loop:
  # ## First Rule - Accepts all traffic generated by the server (lo interface) 
  - -i lo -j ACCEPT
  ## Second Rule - Accepts all traffic that are part 
  ## of an established o related connection
  - -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  ## Third Rule - Allows SSH traffic on port 3344
  - -p tcp --dport {{ SSH_PORT }} -j ACCEPT
  ## Fourth Rule - Arops all other traffic
  - -j DROP
- name: View summary set up in your  firewall
  command: iptables -S
  register: result
- debug:
    msg: "{{result}}"